### ISSUE TITLE
Is wheel building working?

### ISSUE THREAD

**Issue by ejschoen** [equinor/dlisio#287]
We're trying to work around the issues that I mentioned in #278, and until there's a PyPI kit newer than version 0.2.3, we're having to install our fork.  Unfortunately, we're seeing the dl::findoffsets infinite loop at a client site running Centos 7, and we're unable to build the kit natively on that OS, due to conflicts with that OS' older versions of gcc, cmake, etc.   

We thought we'd try building a wheel for installation using a docker container based on Centos 7 and Python 3.6, but we're not sure what the right incantation is.  All of the build instructions from the README.md file work, but this doesn't appear to leave us with a package we can install elsewhere.

Running some variant on `pip wheel` seems to be the right next step, but we can't get past failures related to cmake being able to find sources for mpark.

```
  CMake Error at setup-CMakeLists.txt:10 (find_package):
    By not providing "Findmpark.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "mpark", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "mpark" with any of
    the following names:
  
      mparkConfig.cmake
      mpark-config.cmake
  
    Add the installation prefix of "mpark" to CMAKE_PREFIX_PATH or set
    "mpark_DIR" to a directory containing one of the above files.  If "mpark"
    provides a separate development package or SDK, be sure it has been
    installed.
  Call Stack (most recent call first):
    CMakeLists.txt:6 (include)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-p4mqyivd/_skbuild/linux-x86_64-3.6/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/opt/app-root/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 586, in setup
      languages=cmake_languages
    File "/opt/app-root/lib/python3.6/site-packages/skbuild/cmaker.py", line 240, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))
  
```

I've tried adding a directory reference to mpark in setup.py based on older versions of the file:
```
        # Cmake has issues under dockcross...
        '-Ddlisio_DIR='+src('../build/lib'),
        '-Dmio_DIR='+src('../build/external/mio'),
        '-Dmpark_DIR='+src('../build/external/mpark'),
```
but this doesn't work, as cmake copies the setup files into a temporary area but not the build/external files.  We're not cmake experts, so at this point, we're at a loss for how to successfully package into a wheel.  Is it possible to get some packaging help added to the README file?

**Comment by ErlendHaa** [comment]
Hi

We build our wheel on travis, using [multibuild](https://github.com/matthew-brett/multibuild). The wheels are built in a docker container running the [manylinux1](https://www.python.org/dev/peps/pep-0513/) image. If that is acceptable, you could just setup travis to run on your fork and store the wheels that it creates.

To your issue with `mpark`: If you take a look in [config.sh](https://github.com/equinor/dlisio/blob/master/config.sh) you'll see that we copy `mpark` to `usr/local/include` so that it's properly picked up later on. Depending on you setup, you might want to do something similar.

**Comment by ErlendHaa** [comment]
Hi, Im gonna close this issue now as there has been no activity here for a while. Feel free to re-open if needed.

**Comment by ejschoen** [comment]
Apologies--I hadn't thought to follow up with a response.  Indeed, copying mpark to usr/local/include allows our container builds to complete, and we're able to build both manylinux and Alpine linux containers.
